name: test

on: [push]

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
        include:
          - python: 2.7
            env: py27
          - python: 3.5
            env: py35
          - python: 3.6
            env: py36
          - python: 3.7
            env: py37
          - python: 3.8
            env: py38
          - python: 3.9
            env: py39

    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and other packages
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Make download directories
        run: |
          mkdir -p tests/data/cs
          mkdir tests/baseline_images
      - name: Download baseline images
        uses: wei/curl@v1.1.1
        with:
          args: https://engaging-web.mit.edu/~jahn/MITgcmutils/baseline_images/cs_pcol.png -o tests/baseline_images/cs_pcol.png
      - name: Download mnc output
        uses: wei/curl@v1.1.1
        with:
          args: https://engaging-web.mit.edu/~jahn/MITgcmutils/mnc/global_ocean.cs32x15/run/mnc_test_0001/state.0000072000.t[001-012].nc -o tests/data/cs/state.0000072000.t\#1.nc
      - name: Run Tox
        run: tox -e ${{ matrix.env }}

